export const experienceItems = [
  {
    date: "August 2023 - Present",
    title: "Senior Frontend Engineer",
    company: "Proxet",
    location: "Bogotá D.C., Colombia",
    description: `Migrated applications from Angular 13 to React + TypeScript, developing reusable components and web extensions. Designed mockups and prototypes for new features, improving UX and aligning with business goals.  This included transitioning the main application to React and TypeScript, designing reusable components, developing an autofill web extension, and creating design mockups.`,
  },
  {
    date: "May 2023 - August 2023",
    title: "Senior Angular Developer",
    company: "Newfire Global Partners",
    location: "Remote",
    description: "Developed, maintained, and deployed features for the TruCare application using Angular 13.",
  },
  {
    date: "January 2022 - March 2023",
    title: "Senior Software Engineer, Frontend",
    company: "Terminal Inc",
    location: "Remote",
    description: "Implemented features for therapist platforms using Angular 12+ and maintained an embedded Flutter application. Collaborated with QA and design teams.",
  },
  {
    date: "September 2021 - January 2022",
    title: "Engineer II",
    company: "Commure",
    location: "Remote",
    description: `Researched micro frontends using SingleSPA JS and implemented modular architecture solutions. Built reusable Angular and React components with StencilJS and supported the Listrunner platform using React. This involved researching micro frontends, designing reusable components, and providing platform support.`,
  },
  {
    date: "September 2020 - August 2021",
    title: "Engineer I",
    company: "Commure",
    location: "Bogotá D.C., Colombia",
    description: `Developed features and resolved bugs for the Listrunner platform. Integrated third-party services like Sentry and Intercom, and researched CSS frameworks for scalable component libraries.  This work included implementing features, resolving bugs, integrating third-party services, and researching CSS frameworks.`,
  },
  {
    date: "September 2019 - August 2020",
    title: "Frontend Developer",
    company: "Merlin",
    location: "Bogotá D.C., Colombia",
    description: `Developed and optimized responsive landing and application pages using Angular 7+, Python, and Jinja. Focused on SEO and performance, generating static pages to improve visibility and user engagement.  This involved designing responsive pages, using Python and Jinja for static pages, applying performance optimizations, and implementing SEO best practices.`,
  },
  {
    date: "October 2017 - September 2019",
    title: "Associate Engineer",
    company: "Alert Logic",
    location: "Santiago de Cali, Colombia",
    description: `Developed responsive UIs for Alert Logic products using Angular 5+. Mentored interns, improved test coverage, and contributed to customer-facing projects. Supported the migration of AngularJS apps to Angular 2+. This included designing UIs, mentoring interns, delivering projects, and contributing to application migrations.`,
  },
  {
    date: "July 2016 - July 2017",
    title: "Web Developer Intern",
    company: "Alert Logic",
    location: "Santiago de Cali, Colombia",
    description: `Enhanced software quality by increasing test coverage for PHP and AngularJS applications. Developed new features and applications using PHP and AngularJS within the SCRUM framework. Automated user story documentation.  This included improving test coverage, resolving defects, developing new features, and automating documentation.`,
  },
];